test sync 2

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -30,31 +30,31 @@ jobs:
                 shell: bash
                 working-directory: ./terraform
 
-        steps:
-            - name: "checkout source code"
-                uses: actions/checkout@v4
+    steps:
+        - name: "checkout source code"
+            uses: actions/checkout@v4
 
-            - name: "setup terraform with specified version on the runner"
-                uses: hashicorp/setup-terraform@v2
+        - name: "setup terraform with specified version on the runner"
+            uses: hashicorp/setup-terraform@v2
                 #with:
                 #    terraform_version: 2.0.3  # uncomment will use latest
 
-            - name: "terraform init"
-                id: init
-                run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
+        - name: "terraform init"
+            id: init
+            run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
 
-            - name: "terraform format"
-                id: fmt
-                run: terraform fmt -check   # if format ist not correct deployment will fail
-            - name: "terraform validate"
-                id: validate
-                run: terraform validate
+        - name: "terraform format"
+            id: fmt
+            run: terraform fmt -check   # if format ist not correct deployment will fail
+        - name: "terraform validate"
+            id: validate
+            run: terraform validate
 
-            - name: "terraform plan"
-                id: plan
-                run: terraform plan -no-color -input=false -out planfile
-                continue-on-error: true
+        - name: "terraform plan"
+            id: plan
+            run: terraform plan -no-color -input=false -out planfile
+            continue-on-error: true
 
-            - name: "terraform plan status"
-                if: steps.plan.outcome == 'failure'
-                run: exit 1
+        - name: "terraform plan status"
+            if: steps.plan.outcome == 'failure'
+            run: exit 1
